# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gustavopiovesan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: websockets-cronjobs-serverless-aws

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    CONNECTIONS_TABLE: !Ref ConnectionsTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: !GetAtt ConnectionsTable.Arn

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  wsConnection:
    handler: src/functions/wsConnection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
